language: objective-c
osx_image: xcode7.3
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - IOS_SDK=iphonesimulator9.3
before_install:
  - brew update
  - brew reinstall xctool
xcode_scheme: Debug
script:
  - xcodebuild -showsdks
  - xctool -project Project/Vision.xcodeproj -scheme Debug -sdk $IOS_SDK build analyze
