language: objective-c
before_install:
  - brew update
  - brew reinstall xctool
xcode_scheme: Debug
xcode_sdk:
  - iphonesimulator
  - iphonesimulator9.2
script: xctool -project Project/Vision.xcodeproj -scheme Debug -sdk iphonesimulator9.2 build analyze
